# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppWithHerokuCommunity' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for AppWithHerokuCommunity
  pod 'Firebase'
  pod 'Firebase/Messaging'

  target 'AppWithHerokuCommunityTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
